version: '3.8'

services:
  note-viewer-dev:
    volumes:
      - ./note-viewer:/usr/src/app/
      - /usr/src/app/node_modules
    build:
      context: ./note-viewer
      dockerfile: Dockerfile.dev
    expose:
      - 3000
    # temporary for testing
    ports:
      - '3002:3000'
    networks:
      - notesage-network

  note-viewer-prod:
    volumes:
      - /usr/src/app/node_modules
    build:
      context: ./note-viewer
      dockerfile: Dockerfile.prod
    expose:
      - 3000
    # temporary for testing
    ports:
      - '3002:3000'

  sage-ai-dev:
    volumes:
      - ./sage-ai:/usr/src/app/
      - /usr/src/app/node_modules
    build:
      context: ./sage-ai
      dockerfile: Dockerfile.dev
    expose:
      - 8080
    # temporary for testing
    ports:
      - '8080:8080'
    networks:
      - notesage-network

  sage-ai-prod:
    build:
      context: ./sage-ai
      dockerfile: Dockerfile.prod
    expose:
      - 8080
    # temporary for testing
    ports:
      - '8080:8080'

  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME-localstack_main}'
    image: localstack/localstack:2.2.0
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
    environment:
      - AWS_DEBUG_REGION=us-east-1
      - SERVICES=s3
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './localstack/:/etc/localstack/init/ready.d/' # initializes s3 bucket
    networks:
      - notesage-network

networks:
  notesage-network:
