FROM node:lts-bullseye

# Set node environment to development
ENV NODE_ENV development

# Set working directory of container to be /user/src/app
WORKDIR /usr/src/app

# Copy over package.json and package-lock.json
COPY package*.json /usr/src/app

# Enable permission to cache in node_modules
# RUN mkdir -p /usr/src/app/node_modules/

# Install dependencies
RUN npm install --unsafe-perm

# RUN chown -R node /usr/src/app/node_modules/

# Switch to user 'node' instead of using root user
# USER node

# Start node server
CMD ["npm", "run", "start:watch"]